---
development:
  cloud_name: rmdz
  api_key: 'apkey'
  api_secret: apiSecret
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: rmdz
  api_key: 'apkey'
  api_secret: apiSecret
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: rmdz
  api_key: 'apkey'
  api_secret: apiSecret
  enhance_image_tag: true
  static_file_support: false
